# Sample .travis.yml for R projects

language: r
cache: packages
warnings_are_errors: false
sudo: false




#script: ./travis-tool.sh run_tests

#before_install:
#    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
#    - chmod 755 ./travis-tool.sh
#    - ./travis-tool.sh bootstrap

#install:
#    - ./travis-tool.sh install_deps



