# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

jobs:
  inlcude:
    - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    install:
      - Rscript -e 'devtools::install_deps(dependencies = TRUE, upgrade = "never")'



