# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required

script: ./travis-tool.sh run_tests

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap

install:
    - ./travis-tool.sh install_deps
    - ./travis-tool.sh install_github hadley/devtools
    - ./travis-tool.sh install_github hadley/testthat


on_failure:
    - ./travis-tool.sh dump_logs

env:
  global:
    - CRAN: http://cran.rstudio.com
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - BOOTSTRAP_LATEX=""
