# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r: release
  install:
    - Rscript -e 'devtools::install_deps(dependencies = TRUE, upgrade = "never");


after_success:
  - Rscript -e 'covr::codecov()'
